import { useEffect, useState } from "react";
import { ArrowLeft, Flame, Link as LinkIcon, Trophy } from "lucide-react";
import { Area, AreaChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { api } from "../api";
import { Button } from "./ui/button";
import { Card } from "./ui/card";

const key = (date) => date.toISOString().slice(0, 10);
export function HabitDetail({ habit, onBack }) {
  const [stats, setStats] = useState(null);
  useEffect(() => { api(`/api/habits/${habit.id}/stats`).then(setStats); }, [habit.id]);
  if (!stats) return <div className="p-8 text-center text-ink/55">Cargando progreso...</div>;
  const logs = new Map(stats.logs.map((log) => [log.date, log.completed]));
  const days = Array.from({ length: 84 }, (_, index) => { const d = new Date(); d.setDate(d.getDate() - (83 - index)); return { date: key(d), completed: logs.get(key(d)) }; });
  const chart = Array.from({ length: 30 }, (_, index) => { const d = new Date(); d.setDate(d.getDate() - (29 - index)); return { day: `${d.getDate()}/${d.getMonth() + 1}`, completed: logs.get(key(d)) ? 100 : 0 }; });
  return <main className="mx-auto max-w-5xl px-5 py-8 sm:px-8"><Button variant="ghost" onClick={onBack} className="mb-6 -ml-3 gap-2"><ArrowLeft size={16} />Todos los hábitos</Button><div className="mb-8"><p className="text-xs font-bold uppercase tracking-[.18em] text-moss">{habit.type === "AVOID" ? "Evitar" : "Construir"}</p><h1 className="mt-2 font-serif text-4xl font-bold sm:text-5xl">{habit.name}</h1>{habit.identityStatement && <p className="mt-3 text-lg text-ink/65">{habit.identityStatement}</p>}{habit.stackedAfter && <p className="mt-4 inline-flex items-center gap-2 rounded-full bg-moss/10 px-3 py-1.5 text-sm font-medium text-moss"><LinkIcon size={14} />Después de: {habit.stackedAfter.name} <span>→</span> {habit.name}</p>}</div><div className="grid gap-4 sm:grid-cols-3"><Metric icon={<Flame />} value={stats.currentStreak} label="racha actual" /><Metric icon={<Trophy />} value={stats.longestStreak} label="mejor racha" /><Metric icon={<span className="text-xl font-bold">%</span>} value={stats.completionRate30d} label="cumplimiento, 30 días" /></div><Card className="mt-5 p-5 sm:p-7"><h2 className="font-serif text-xl font-bold">Tu constancia</h2><p className="mt-1 text-sm text-ink/55">Las últimas 12 semanas. Verde significa cumplido.</p><div className="mt-6 grid grid-flow-col grid-rows-7 justify-start gap-1.5 overflow-x-auto pb-2">{days.map((day) => <div title={`${day.date}: ${day.completed ? "cumplido" : "sin registrar"}`} key={day.date} className={`h-4 w-4 rounded-[3px] ${day.completed ? "bg-moss" : day.completed === false ? "bg-red-200" : "bg-sand"}`} />)}</div><div className="mt-3 flex items-center gap-3 text-xs text-ink/50"><i className="h-3 w-3 rounded-sm bg-sand" />Sin registro <i className="h-3 w-3 rounded-sm bg-red-200" />No cumplido <i className="h-3 w-3 rounded-sm bg-moss" />Cumplido</div></Card><Card className="mt-5 p-5 sm:p-7"><h2 className="font-serif text-xl font-bold">Ritmo de los últimos 30 días</h2><div className="mt-5 h-56"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chart}><defs><linearGradient id="progress" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#28634a" stopOpacity=".35" /><stop offset="100%" stopColor="#28634a" stopOpacity="0" /></linearGradient></defs><XAxis dataKey="day" tickLine={false} axisLine={false} tick={{ fontSize: 11 }} interval={4} /><YAxis hide domain={[0, 100]} /><Tooltip formatter={(value) => [`${value}%`, "Cumplimiento"]} /><Area type="step" dataKey="completed" stroke="#28634a" strokeWidth={2} fill="url(#progress)" /></AreaChart></ResponsiveContainer></div></Card></main>;
}
function Metric({ icon, value, label }) { return <Card className="flex items-center gap-4 p-5"><span className="text-moss">{icon}</span><div><strong className="block text-2xl">{value}</strong><span className="text-sm text-ink/55">{label}</span></div></Card>; }
